data = [
    # --- ХРАНА ---
    {"product_name": "ЛЕБ", "category": "Храна"},
    {"product_name": "ЧОКОЛАДО", "category": "Храна"},
    {"product_name": "ЧОКОЛАДО МИЛКА", "category": "Храна"},
    {"product_name": "КЕКС ПЛАЗМА", "category": "Храна"},
    {"product_name": "ЈАЈЦА", "category": "Храна"},
    {"product_name": "ТЕСТЕНИНИ", "category": "Храна"},
    {"product_name": "БОНБОНИ", "category": "Храна"},
    {"product_name": "МАСЛИНОВО МАСЛО", "category": "Храна"},
    {"product_name": "ШЕЌЕР", "category": "Храна"},
    {"product_name": "СОЛ", "category": "Храна"},
    {"product_name": "ПАВЛАКА", "category": "Храна"},
    {"product_name": "СМЕТАНА", "category": "Храна"},
    {"product_name": "СИРЕЊЕ МОЦАРЕЛА", "category": "Храна"},
    {"product_name": "СИРЕЊЕ КАШКАВАЛ", "category": "Храна"},
    {"product_name": "КРЕМ СИРЕЊЕ", "category": "Храна"},
    {"product_name": "МАСЛО ЗА ГОТВЕЊЕ", "category": "Храна"},
    {"product_name": "ПЕЦИВО", "category": "Храна"},
    {"product_name": "СВЕЖО МЕСО", "category": "Храна"},
    {"product_name": "ПИЛЕШКО МЕСО", "category": "Храна"},
    {"product_name": "СВИНСКО МЕСО", "category": "Храна"},
    {"product_name": "ОВЧО МЕСО", "category": "Храна"},
    {"product_name": "ГОВЕДСКО МЕСО", "category": "Храна"},
    {"product_name": "РИКОТА СИРЕЊЕ", "category": "Храна"},
    {"product_name": "ЈОГУРТ", "category": "Храна"},
    {"product_name": "ЈОГУРТ СО ОВОШЈЕ", "category": "Храна"},
    {"product_name": "СПАГЕТИ", "category": "Храна"},
    {"product_name": "МАКАРОНИ", "category": "Храна"},
    {"product_name": "САЛАТА МИКС", "category": "Храна"},
    {"product_name": "КУКУРУЗ КОНЗЕРВА", "category": "Храна"},
    {"product_name": "ГРАШОК КОНЗЕРВА", "category": "Храна"},
    {"product_name": "ДОМАТИ КОНЗЕРВА", "category": "Храна"},
    {"product_name": "ОРИЗ", "category": "Храна"},
    {"product_name": "БРАШНО", "category": "Храна"},
    {"product_name": "ПЕЧУРКИ", "category": "Храна"},
    {"product_name": "ЈАБОЛКА", "category": "Храна"},
    {"product_name": "БАНАНИ", "category": "Храна"},
    {"product_name": "ПОРТОКАЛИ", "category": "Храна"},
    {"product_name": "КРОМИД", "category": "Храна"},
    {"product_name": "КОМПИР", "category": "Храна"},
    {"product_name": "МОРКОВ", "category": "Храна"},
    {"product_name": "ДОМАТИ", "category": "Храна"},
    {"product_name": "КРАСТАВИЦИ", "category": "Храна"},
    {"product_name": "СЛАНИНА", "category": "Храна"},
    {"product_name": "КОЛБАСИ", "category": "Храна"},
    {"product_name": "РИБА", "category": "Храна"},
    {"product_name": "ТУНА", "category": "Храна"},

    # --- ПИЈАЛОЦИ ---
    {"product_name": "МЛЕКО", "category": "Пијалоци"},
    {"product_name": "ВОДА", "category": "Пијалоци"},
    {"product_name": "ГАЗИРАНА ВОДА", "category": "Пијалоци"},
    {"product_name": "МИНЕРАЛНА ВОДА", "category": "Пијалоци"},
    {"product_name": "НЕГАЗИРАНА ВОДА", "category": "Пијалоци"},
    {"product_name": "КАФЕ", "category": "Пијалоци"},
    {"product_name": "ЛЕДЕНО КАФЕ", "category": "Пијалоци"},
    {"product_name": "ЧАЈ", "category": "Пијалоци"},
    {"product_name": "СОК", "category": "Пијалоци"},
    {"product_name": "ЈАБОЛКОВ СОК", "category": "Пијалоци"},
    {"product_name": "ПОРТОКАЛОВ СОК", "category": "Пијалоци"},
    {"product_name": "ГРОЗОВ СОК", "category": "Пијалоци"},
    {"product_name": "КОЛА", "category": "Пијалоци"},
    {"product_name": "ЕНЕРГЕТСКИ НАПИТОК", "category": "Пијалоци"},
    {"product_name": "ПИВО СВЕТЛО", "category": "Пијалоци"},
    {"product_name": "ПИВО ТЕМНО", "category": "Пијалоци"},
    {"product_name": "ВИНО ЦРНО", "category": "Пијалоци"},
    {"product_name": "ВИНО БЕЛО", "category": "Пијалоци"},
    {"product_name": "РАКИЈА", "category": "Пијалоци"},
    {"product_name": "ВИСКИ", "category": "Пијалоци"},

    # --- КОЗМЕТИКА ---
    {"product_name": "ШАМПОН", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА РАЦЕ", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА ТЕЛО", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА СОНЦЕ", "category": "Козметика"},
    {"product_name": "ЛОСИОН ЗА ТЕЛО", "category": "Козметика"},
    {"product_name": "ТОАЛЕТНА ВОДА", "category": "Козметика"},
    {"product_name": "МАСКА ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "ПАРФЕМ", "category": "Козметика"},
    {"product_name": "ШМИНКА", "category": "Козметика"},
    {"product_name": "МАСКАРА", "category": "Козметика"},
    {"product_name": "ПУДРА", "category": "Козметика"},
    {"product_name": "СЕРУМ ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "НОЌЕН КРЕМ", "category": "Козметика"},
    {"product_name": "ДНЕВЕН КРЕМ", "category": "Козметика"},
    {"product_name": "БАЛСАМ ЗА УСНИ", "category": "Козметика"},
    {"product_name": "ГЕЛ ЗА ТУШИРАЊЕ", "category": "Козметика"},
    {"product_name": "ТЕЧЕН САПУН", "category": "Козметика"},

    # --- ДОМАЌИНСТВО ---
    {"product_name": "САПУН", "category": "Домаќинство"},
    {"product_name": "ДЕТЕРГЕНТ", "category": "Домаќинство"},
    {"product_name": "ОМЕКНУВАЧ", "category": "Домаќинство"},
    {"product_name": "ТОАЛЕТНА ХАРТИЈА", "category": "Домаќинство"},
    {"product_name": "ХАРТИЕНИ САЛФЕТКИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА САДОВИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА ПРОЗОРЦИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА ПОДОВИ", "category": "Домаќинство"},
    {"product_name": "БЕЛИНА", "category": "Домаќинство"},
    {"product_name": "СУНЃЕРИ ЗА МИЕЊЕ", "category": "Домаќинство"},
    {"product_name": "РАКАВИЦИ ЗА МИЕЊЕ", "category": "Домаќинство"},
    {"product_name": "ЧЕТКА ЗА ЗАБИ", "category": "Домаќинство"},
    {"product_name": "ПАСТА ЗА ЗАБИ", "category": "Домаќинство"},
    {"product_name": "ПЕЛЕНИ", "category": "Домаќинство"},
    {"product_name": "ЃУБРЕТАРСКИ КЕСИ", "category": "Домаќинство"},
    {"product_name": "АЛУМИНИУМСКА ФОЛИЈА", "category": "Домаќинство"},
    {"product_name": "ПЛАСТИЧНА ФОЛИЈА", "category": "Домаќинство"},

    # --- ЕЛЕКТРОНИКА ---
    {"product_name": "ТЕЛЕВИЗОР", "category": "Електроника"},
    {"product_name": "МОБИЛЕН ТЕЛЕФОН", "category": "Електроника"},
    {"product_name": "ЛАПТОП", "category": "Електроника"},
    {"product_name": "МИКРОБРАН", "category": "Електроника"},
    {"product_name": "ФРИЖИДЕР", "category": "Електроника"},
    {"product_name": "ПЕГЛА", "category": "Електроника"},
    {"product_name": "КОМПЈУТЕРСКА ГЛУВЧКА", "category": "Електроника"},
    {"product_name": "ПЕЧКА", "category": "Електроника"},
    {"product_name": "МАШИНА ЗА ПЕРЕЊЕ", "category": "Електроника"},
    {"product_name": "МАШИНА ЗА САДОВИ", "category": "Електроника"},
    {"product_name": "ЗАМРЗНУВАЧ", "category": "Електроника"},
    {"product_name": "КЛИМА", "category": "Електроника"},
    {"product_name": "ЗВУЧНИК", "category": "Електроника"},
    {"product_name": "СЛУШАЛКИ", "category": "Електроника"},
    {"product_name": "КАБЕЛ", "category": "Електроника"},
    {"product_name": "БАТЕРИИ", "category": "Електроника"},
    {"product_name": "ПОЛНАЧ", "category": "Електроника"},

    # --- ДРУГО ---
    {"product_name": "ЧАДОР", "category": "Друго"},
    {"product_name": "ИГРАЧКА", "category": "Друго"},
    {"product_name": "ПЕНКАЛО", "category": "Друго"},
    {"product_name": "ТЕТРАТКА", "category": "Друго"},
    {"product_name": "КНИГА", "category": "Друго"},
    {"product_name": "ЦВЕЌЕ", "category": "Друго"},
    {"product_name": "ШИШЕ ЗА ВОДА", "category": "Друго"},
    {"product_name": "ТОРБА za", "category": "Друго"},
    {"product_name": "РАНЕЦ ", "category": "Друго"},
    {"product_name": "РЕМЕН", "category": "Друго"},
    {"product_name": "ЧОРАПИ", "category": "Друго"},
    {"product_name": "МАИЦА", "category": "Друго"},
    {"product_name": "ПАНТАЛОНИ", "category": "Друго"},
    {"product_name": "ЈАКНА", "category": "Друго"},
    {"product_name": "ЧЕВЛИ", "category": "Друго"},
    {"product_name": "КАПА", "category": "Друго"},
    {"product_name": "ОЧИЛА", "category": "Друго"},
    {"product_name": "ЧАСОВНИК", "category": "Друго"},
    {"product_name": "СВЕЌА", "category": "Друго"},
    {"product_name": "ВАЗНА", "category": "Друго"},
    {"product_name": "МАГНЕТ", "category": "Друго"}
]