data = [
    # --- ХРАНА ---
    {"product_name": "ЛЕБ", "category": "Храна"},
    {"product_name": "БЕЛО ЛЕБЧЕ", "category": "Храна"},
    {"product_name": "ИНТЕГРАЛЕН ЛЕБ", "category": "Храна"},
    {"product_name": "ПОГАЧА", "category": "Храна"},
    {"product_name": "БУРЕК", "category": "Храна"},
    {"product_name": "ЧОКОЛАДО", "category": "Храна"},
    {"product_name": "ЧОКОЛАДО МИЛКА", "category": "Храна"},
    {"product_name": "ЧОКОЛАДНО", "category": "Храна"},
    {"product_name": "ТЕМНО ЧОКОЛАДО", "category": "Храна"},
    {"product_name": "БЕЛО ЧОКОЛАДО", "category": "Храна"},
    {"product_name": "КЕКС ПЛАЗМА", "category": "Храна"},
    {"product_name": "ВАФЛИ", "category": "Храна"},
    {"product_name": "БИСКВИТИ", "category": "Храна"},
    {"product_name": "ЈАЈЦА", "category": "Храна"},
    {"product_name": "ОРГАНСКИ ЈАЈЦА", "category": "Храна"},
    {"product_name": "ТЕСТЕНИНИ", "category": "Храна"},
    {"product_name": "ШПАГЕТИ", "category": "Храна"},
    {"product_name": "МАКАРОНИ", "category": "Храна"},
    {"product_name": "СВЕЖО ПЕЧЕНИ", "category": "Храна"},
    {"product_name": "БОНБОНИ", "category": "Храна"},
    {"product_name": "БОНБОНИ МЕНТОС", "category": "Храна"},
    {"product_name": "ГУМЕНИ БОНБОНИ", "category": "Храна"},
    {"product_name": "МАСЛИНОВО МАСЛО", "category": "Храна"},
    {"product_name": "СОНЧОГЛЕДОВО МАСЛО", "category": "Храна"},
    {"product_name": "КОКОСОВО МАСЛО", "category": "Храна"},
    {"product_name": "ШЕЌЕР", "category": "Храна"},
    {"product_name": "ВЕЛ ШЕЌЕР", "category": "Храна"},
    {"product_name": "ШЕЌЕР КЕФЕАВ", "category": "Храна"},
    {"product_name": "МЕД", "category": "Храна"},
    {"product_name": "СОЛ", "category": "Храна"},
    {"product_name": "МОРСКА СОЛ", "category": "Храна"},
    {"product_name": "ПАВЛАКА", "category": "Храна"},
    {"product_name": "КИСЕЛА ПАВЛАКА", "category": "Храна"},
    {"product_name": "СЛАТКА ПАВЛАКА", "category": "Храна"},
    {"product_name": "СИРЕЊЕ МОЦАРЕЛА", "category": "Храна"},
    {"product_name": "СИРЕЊЕ КАШКАВАЛ", "category": "Храна"},
    {"product_name": "КРЕМ СИРЕЊЕ", "category": "Храна"},
    {"product_name": "РИКОТА СИРЕЊЕ", "category": "Храна"},
    {"product_name": "ПАРМЕЗАН", "category": "Храна"},
    {"product_name": "ФЕТА СИРЕЊЕ", "category": "Храна"},
    {"product_name": "МЛАДО СИРЕЊЕ", "category": "Храна"},
    {"product_name": "МАСЛО ЗА ГОТВЕЊЕ", "category": "Храна"},
    {"product_name": "ПУТЕР", "category": "Храна"},
    {"product_name": "МАРГАРИН", "category": "Храна"},
    {"product_name": "ПЕЦИВО", "category": "Храна"},
    {"product_name": "КРОФНИ", "category": "Храна"},
    {"product_name": "ТОРТА", "category": "Храна"},
    {"product_name": "СЛАТКО ЛУТО", "category": "Храна"},
    {"product_name": "ЧИЛИ", "category": "Храна"},
    {"product_name": "КОЛАЧИ", "category": "Храна"},
    {"product_name": "СВЕЖО МЕСО", "category": "Храна"},
    {"product_name": "ПИЛЕШКО МЕСО", "category": "Храна"},
    {"product_name": "ПИЛЕШКО ФИЛЕ", "category": "Храна"},
    {"product_name": "ПИПЕШКИ БАТАК", "category": "Храна"},
    {"product_name": "ПИЛЕШКИ КРИЛЦА", "category": "Храна"},
    {"product_name": "СВИНСКО МЕСО", "category": "Храна"},
    {"product_name": "СВИНСКА КОТЛЕТА", "category": "Храна"},
    {"product_name": "СВИНСКА ВРАТИНА", "category": "Храна"},
    {"product_name": "ОВЧО МЕСО", "category": "Храна"},
    {"product_name": "ЈАГНЕШКО МЕСО", "category": "Храна"},
    {"product_name": "ГОВЕДСКО МЕСО", "category": "Храна"},
    {"product_name": "ГОВЕДСКИ СТЕК", "category": "Храна"},
    {"product_name": "МЕЛЕНО МЕСО", "category": "Храна"},
    {"product_name": "ЈОГУРТ", "category": "Храна"},
    {"product_name": "ЈОГУРТ СО ОВОШЈЕ", "category": "Храна"},
    {"product_name": "ГРЧКИ ЈОГУРТ", "category": "Храна"},
    {"product_name": "ПРИРОДЕН ЈОГУРТ", "category": "Храна"},
    {"product_name": "САЛАТА МИКС", "category": "Храна"},
    {"product_name": "РУКОЛА", "category": "Храна"},
    {"product_name": "СПАНАЌ", "category": "Храна"},
    {"product_name": "ЗЕЛКА", "category": "Храна"},
    {"product_name": "ЦРВЕНА ЗЕЛКА", "category": "Храна"},
    {"product_name": "КАРФИОЛ", "category": "Храна"},
    {"product_name": "БРОКУЛИ", "category": "Храна"},
    {"product_name": "КОНЗЕРВИ ХРАНА", "category": "Храна"},
    {"product_name": "ГРАШОК КОНЗЕРВА", "category": "Храна"},
    {"product_name": "ГРАШОК ЗАМРЗНАТ", "category": "Храна"},
    {"product_name": "ДОМАТИ КОНЗЕРВА", "category": "Храна"},
    {"product_name": "ДОМАТЕН СОС", "category": "Храна"},
    {"product_name": "ДОМАТЕНО ПИРЕ", "category": "Храна"},
    {"product_name": "ОРИЗ", "category": "Храна"},
    {"product_name": "ИНТЕГРАЛЕН ОРИЗ", "category": "Храна"},
    {"product_name": "БРАШНО", "category": "Храна"},
    {"product_name": "ИНТЕГРАЛНО БРАШНО", "category": "Храна"},
    {"product_name": "БРАШНО ТИП 400", "category": "Храна"},
    {"product_name": "БРАШНО ТИП 500", "category": "Храна"},
    {"product_name": "ПЕЧУРКИ", "category": "Храна"},
    {"product_name": "ШАМПИЊОНИ", "category": "Храна"},
    {"product_name": "ЈАБОЛКА", "category": "Храна"},
    {"product_name": "ЦРВЕНИ ЈАБОЛКИ", "category": "Храна"},
    {"product_name": "ЗЕЛЕНИ ЈАБОЛКИ", "category": "Храна"},
    {"product_name": "БАНАНИ", "category": "Храна"},
    {"product_name": "ПОРТОКАЛИ", "category": "Храна"},
    {"product_name": "МАНДАРИНИ", "category": "Храна"},
    {"product_name": "ЛИМОНИ", "category": "Храна"},
    {"product_name": "КИВИ", "category": "Храна"},
    {"product_name": "ЈАГОДИ", "category": "Храна"},
    {"product_name": "ГРОЗЈЕ", "category": "Храна"},
    {"product_name": "ПРАСКИ", "category": "Храна"},
    {"product_name": "КАЈСИИ", "category": "Храна"},
    {"product_name": "КРОМИД", "category": "Храна"},
    {"product_name": "ЦРВЕН КРОМИД", "category": "Храна"},
    {"product_name": "БИЈАЛ КРОМИД", "category": "Храна"},
    {"product_name": "КОМПИР", "category": "Храна"},
    {"product_name": "МЛАД КОМПИР", "category": "Храна"},
    {"product_name": "СЛАДОК КОМПИР", "category": "Храна"},
    {"product_name": "МОРКОВ", "category": "Храна"},
    {"product_name": "ДОМАТ", "category": "Храна"},
    {"product_name": "ЧЕРИ ДОМАТИ", "category": "Храна"},
    {"product_name": "КРАСТАВИЦИ", "category": "Храна"},
    {"product_name": "КИСЕЛИ КРАСТАВИЧКИ", "category": "Храна"},
    {"product_name": "ПИПЕРКИ", "category": "Храна"},
    {"product_name": "ЉУТИ ДИМЕНО", "category": "Храна"},
    {"product_name": "МАГДОНОС", "category": "Храна"},
    {"product_name": "СЛАНИНА", "category": "Храна"},
    {"product_name": "КОЛБАСИ", "category": "Храна"},
    {"product_name": "ВИРШЛИ", "category": "Храна"},
    {"product_name": "КУЛЕН", "category": "Храна"},
    {"product_name": "РИБА", "category": "Храна"},
    {"product_name": "СВЕЖА РИБА", "category": "Храна"},
    {"product_name": "ЗАМРЗНАТА РИБА", "category": "Храна"},
    {"product_name": "ТУНА", "category": "Храна"},
    {"product_name": "САРДИНИ", "category": "Храна"},
    {"product_name": "ЛОСОС", "category": "Храна"},
    {"product_name": "СКУШИ", "category": "Храна"},
    {"product_name": "ОРЕВ", "category": "Храна"},
    {"product_name": "БАДЕМИ", "category": "Храна"},
    {"product_name": "ЛЕНКИ", "category": "Храна"},
    {"product_name": "СОНЧОГЛЕДОВИ СЕМКИ", "category": "Храна"},
    {"product_name": "ТИКВИЧКИ СЕМКИ", "category": "Храна"},
    {"product_name": "СУВО ГРОЗЈЕ", "category": "Храна"},
    {"product_name": "СУВИ КАЈСИИ", "category": "Храна"},
    {"product_name": "СЕНФ", "category": "Храна"},
    {"product_name": "КЕТЧАП", "category": "Храна"},
    {"product_name": "МАЈОНЕЗ", "category": "Храна"},
    {"product_name": "ОЦЕТ", "category": "Храна"},
    {"product_name": "БИЛКОВИ ЗАЧИНИ", "category": "Храна"},
    {"product_name": "ЦРВЕНА БИБЕР", "category": "Храна"},
    {"product_name": "ЧАДЕНО МЕСО", "category": "Храна"},

    # --- ПИЈАЛОЦИ ---
    {"product_name": "МЛЕКО", "category": "Пијалоци"},
    {"product_name": "СВЕЖО МЛЕКО", "category": "Пијалоци"},
    {"product_name": "ОБЕЗМАСЛЕНО МЛЕКО", "category": "Пијалоци"},
    {"product_name": "ПОЛУОБЕЗМАСЛЕНО МЛЕКО", "category": "Пијалоци"},
    {"product_name": "КОЗЈО МЛЕКО", "category": "Пијалоци"},
    {"product_name": "СОЈА МЛЕКО", "category": "Пијалоци"},
    {"product_name": "ОВЕСНО МЛЕКО", "category": "Пијалоци"},
    {"product_name": "БАДЕМОВО МЛЕКО", "category": "Пијалоци"},
    {"product_name": "ВОДА", "category": "Пијалоци"},
    {"product_name": "ЛАДНА ВОДА", "category": "Пијалоци"},
    {"product_name": "ИЗВОРСКА ВОДА", "category": "Пијалоци"},
    {"product_name": "ПЕЛИСТЕРКА ПЕЛИСЕРСКА", "category": "Пијалоци"},
    {"product_name": "ГАЗИРАНА ВОДА", "category": "Пијалоци"},
    {"product_name": "МИНЕРАЛНА ВОДА", "category": "Пијалоци"},
    {"product_name": "ВОДА НЕГАЗИРАНА", "category": "Пијалоци"},
    {"product_name": "НЕГАЗИРАНА ВОДА ", "category": "Пијалоци"},
    {"product_name": "АРОМАТИЗИРАНА ВОДА", "category": "Пијалоци"},
    {"product_name": "КАФЕ", "category": "Пијалоци"},
    {"product_name": "ЦРНО КАФЕ", "category": "Пијалоци"},
    {"product_name": "КАПУЧИНО", "category": "Пијалоци"},
    {"product_name": "ЛАТТЕ", "category": "Пијалоци"},
    {"product_name": "ЕСПРЕСО", "category": "Пијалоци"},
    {"product_name": "ЛЕДЕНО КАФЕ", "category": "Пијалоци"},
    {"product_name": "ИНСТАНТ КАФЕ", "category": "Пијалоци"},
    {"product_name": "ТУРСКО КАФЕ", "category": "Пијалоци"},
    {"product_name": "ЧАЈ", "category": "Пијалоци"},
    {"product_name": "ЗЕЛЕН ЧАЈ", "category": "Пијалоци"},
    {"product_name": "ЦРВЕН ЧАЈ", "category": "Пијалоци"},
    {"product_name": "БИЛКОВ ЧАЈ", "category": "Пијалоци"},
    {"product_name": "НАНЕ ЧАЈ", "category": "Пијалоци"},
    {"product_name": "ЛИМОНОВ ЧАЈ", "category": "Пијалоци"},
    {"product_name": "СОК", "category": "Пијалоци"},
    {"product_name": "ПРИРОДЕН СОК", "category": "Пијалоци"},
    {"product_name": "СОК 100%", "category": "Пијалоци"},
    {"product_name": "ЈАБОЛКОВ СОК", "category": "Пијалоци"},
    {"product_name": "ПОРТОКАЛОВ СОК", "category": "Пијалоци"},
    {"product_name": "ДОМАШЕН СОК", "category": "Пијалоци"},
    {"product_name": "МУЛТИВИТАМИНСКИ СОК", "category": "Пијалоци"},
    {"product_name": "КОКА КОЛА", "category": "Пијалоци"},
    {"product_name": "ПЕПСИ", "category": "Пијалоци"},
    {"product_name": "ФАНТА", "category": "Пијалоци"},
    {"product_name": "СПРАЈТ", "category": "Пијалоци"},
    {"product_name": "ШВЕПС", "category": "Пијалоци"},
    {"product_name": "ЕНЕРГЕТСКИ НАПИТОК", "category": "Пијалоци"},
    {"product_name": "РЕД БУЛ", "category": "Пијалоци"},
    {"product_name": "ПИВО СВЕТЛО", "category": "Пијалоци"},
    {"product_name": "ПИВО ТЕМНО", "category": "Пијалоци"},
    {"product_name": "СКОПСКО ПИВО", "category": "Пијалоци"},
    {"product_name": "ЗЛАТО ПИВО", "category": "Пијалоци"},
    {"product_name": "ХАЈНИКЕН", "category": "Пијалоци"},
    {"product_name": "ВИНО ЦРНО", "category": "Пијалоци"},
    {"product_name": "ВИНО БЕЛО", "category": "Пијалоци"},
    {"product_name": "ВИНО РОЗЕ", "category": "Пијалоци"},
    {"product_name": "ТИКВЕШ ВИНО", "category": "Пијалоци"},
    {"product_name": "РАКИЈА", "category": "Пијалоци"},
    {"product_name": "ВИСКИ", "category": "Пијалоци"},
    {"product_name": "ВОДКА", "category": "Пијалоци"},
    {"product_name": "ЃИН", "category": "Пијалоци"},

    # --- КОЗМЕТИКА ---
    {"product_name": "ШАМПОН", "category": "Козметика"},
    {"product_name": "ШАМПОН ЗА МРСНА КОСА", "category": "Козметика"},
    {"product_name": "ШАМПОН ЗА СУВА КОСА", "category": "Козметика"},
    {"product_name": "ДЕТСКИ ШАМПОН", "category": "Козметика"},
    {"product_name": "БАЛСАМ ЗА КОСА", "category": "Козметика"},
    {"product_name": "МАСКА ЗА КОСА", "category": "Козметика"},
    {"product_name": "ГЕЛ ЗА КОСА", "category": "Козметика"},
    {"product_name": "СПРЕЈ ЗА КОСА", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "ХИДРАТАНТЕН КРЕМ", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА ЧУВСТВИТЕЛНА КОЖА", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА РАЦЕ", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА СТАПАЛА", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА ТЕЛО", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА СОНЦЕ", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА СОНЦЕ СПФ 30", "category": "Козметика"},
    {"product_name": "ЛОСИОН ЗА ТЕЛО", "category": "Козметика"},
    {"product_name": "ТОАЛЕТНА ВОДА", "category": "Козметика"},
    {"product_name": "МАСЛО ЗА ТЕЛО", "category": "Козметика"},
    {"product_name": "МАСКА ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "ПИЛИНГ ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "МИЦЕЛАРНА ВОДА", "category": "Козметика"},
    {"product_name": "ТОНЕР ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "ПАРФЕМ", "category": "Козметика"},
    {"product_name": "ДЕЗОДОРАНС", "category": "Козметика"},
    {"product_name": "ДЕО", "category": "Козметика"},
    {"product_name": "АНТИПЕРСПИРАНС", "category": "Козметика"},
    {"product_name": "ШМИНКА", "category": "Козметика"},
    {"product_name": "МАСКАРА", "category": "Козметика"},
    {"product_name": "СЕНКИ ЗА ОЧИ", "category": "Козметика"},
    {"product_name": "МОЛИВ ЗА ОЧИ", "category": "Козметика"},
    {"product_name": "ПУДРА", "category": "Козметика"},
    {"product_name": "КОМПАКТНА ПУДРА", "category": "Козметика"},
    {"product_name": "РУМЕНИЛО", "category": "Козметика"},
    {"product_name": "КАРМИН", "category": "Козметика"},
    {"product_name": "МОЛИВ ЗА УСНИ", "category": "Козметика"},
    {"product_name": "СЕРУМ ЗА ЛИЦЕ", "category": "Козметика"},
    {"product_name": "НОЌЕН КРЕМ", "category": "Козметика"},
    {"product_name": "ДНЕВЕН КРЕМ", "category": "Козметика"},
    {"product_name": "КРЕМ ЗА ОЧИ", "category": "Козметика"},
    {"product_name": "БАЛСАМ ЗА УСНИ", "category": "Козметика"},


    # --- ХИГИЕНА ---
    {"product_name": "ГЕЛ ЗА ТУШИРАЊЕ", "category": "Козметика"},
    {"product_name": "ПЕНА ЗА БАЊАЊЕ", "category": "Козметика"},
    {"product_name": "ТЕЧЕН САПУН", "category": "Козметика"},
    {"product_name": "АНТИБАКТЕРИСКИ ГЕЛ", "category": "Козметика"},
    {"product_name": "ГЕЛ ЗА РАЦЕ", "category": "Козметика"},
    {"product_name": "ЧЕТКА ЗА ЗАБИ", "category": "Хигиена"},
    {"product_name": "ЕЛЕКТРИЧНА ЧЕТКА ЗА ЗАБИ", "category": "Хигиена"},
    {"product_name": "ДЕТСКА ЧЕТКА ЗА ЗАБИ", "category": "Хигиена"},
    {"product_name": "ПАСТА ЗА ЗАБИ", "category": "Хигиена"},
    {"product_name": "ДЕТСКА ПАСТА ЗА ЗАБИ", "category": "Хигиена"},
    {"product_name": "ИЗБЕЛУВАЧКА ПАСТА ЗА ЗАБИ", "category": "Хигиена"},
    {"product_name": "ПАСТА ЗА ЧУВСТВИТЕЛНИ ЗАБИ", "category": "Хигиена"},
    {"product_name": "ВОДА ЗА УСТА", "category": "Хигиена"},
    {"product_name": "АНТИБАКТЕРИСКА ВОДА ЗА УСТА", "category": "Хигиена"},
    {"product_name": "ОСВЕЖУВАЧКА ВОДА ЗА УСТА", "category": "Хигиена"},
    {"product_name": "КОНЕЦ ЗА ЗАБИ", "category": "Хигиена"},
    {"product_name": "ПЕЛЕНИ", "category": "Хигиена"},
    {"product_name": "БЕБЕШКИ ПЕЛЕНИ", "category": "Хигиена"},
    {"product_name": "ВЛАЖНИ МАРАМЧИЊА", "category": "Хигиена"},
    {"product_name": "ВЛАЖНИ МАРАМЧИЊА ЗА БЕБЕ", "category": "Хигиена"},
    {"product_name": "АНТИБАКТЕРИСКИ ВЛАЖНИ МАРАМЧИЊА", "category": "Хигиена"},
    {"product_name": "ДНЕВНИ ВЛОШКИ", "category": "Хигиена"},
    {"product_name": "НОЌНИ ВЛОШКИ", "category": "Хигиена"},
    {"product_name": "ДАМСКИ ТАМПОНИ", "category": "Хигиена"},
    {"product_name": "ХАРТИЕНИ САЛФЕТКИ", "category": "Хигиена"},
    {"product_name": "МАРАМЧИЊА", "category": "Хигиена"},
    {"product_name": "ВЛАЖНИ САЛФЕТКИ", "category": "Хигиена"},
    {"product_name": "АНТИСЕПТИЧКИ ГЕЛ", "category": "Хигиена"},
    {"product_name": "ГЕЛ ЗА ДЕЗИНФЕКЦИЈА", "category": "Хигиена"},
    {"product_name": "АЛКОХОЛЕН ГЕЛ ЗА РАЦЕ", "category": "Хигиена"},
    {"product_name": "АНТИБАКТЕРИСКИ ГЕЛ", "category": "Хигиена"},
    {"product_name": "ДЕЗОДОРАНС", "category": "Хигиена"},
    {"product_name": "РОЛОН ДЕЗОДОРАНС", "category": "Хигиена"},
    {"product_name": "СПРЕЈ ДЕЗОДОРАНС", "category": "Хигиена"},
    {"product_name": "СТИК ДЕЗОДОРАНС", "category": "Хигиена"},
    {"product_name": "АНТИПЕРСПИРАНС", "category": "Хигиена"},
    {"product_name": "ПРИРОДЕН ДЕЗОДОРАНС", "category": "Хигиена"},
    {"product_name": "ДЕТСКИ ДЕЗОДОРАНС", "category": "Хигиена"},
    {"product_name": "ИНТИМНИ ВЛАЖНИ МАРАМЧИЊА", "category": "Хигиена"},
    {"product_name": "ПЕНА ЗА БРИЧЕЊЕ", "category": "Хигиена"},
    {"product_name": "ГЕЛ ЗА БРИЧЕЊЕ", "category": "Хигиена"},
    {"product_name": "БАЛСАМ ПОСЛЕ БРИЧЕЊЕ", "category": "Хигиена"},
    {"product_name": "СТАПЧИЊА ЗА УШИ", "category": "Хигиена"},
    {"product_name": "ПАМУЧНИ СТАПЧИЊА", "category": "Хигиена"},
    {"product_name": "ГАЗА", "category": "Хигиена"},
    {"product_name": "ФЛАСТЕРИ", "category": "Хигиена"},
    {"product_name": "ДЕТСКИ ФЛАСТЕРИ", "category": "Хигиена"},
    {"product_name": "ВОДООТПОРНИ ФЛАСТЕРИ", "category": "Хигиена"},
    {"product_name": "ЕЛАСТИЧНИ ЗАВОИ", "category": "Хигиена"},
    {"product_name": "ДЕЗИНФЕКЦИСКО СРЕДСТВО", "category": "Хигиена"},
    {"product_name": "АЛКОХОЛ ЗА ДЕЗИНФЕКЦИЈА", "category": "Хигиена"},
    {"product_name": "МАНИКИР СЕТ", "category": "Хигиена"},
    {"product_name": "ПЕДИКИР СЕТ", "category": "Хигиена"},
    {"product_name": "ПИЛА ЗА НОКТИ", "category": "Хигиена"},
    {"product_name": "ЧЕТКА ЗА ТЕЛО", "category": "Хигиена"},
    {"product_name": "СУНЃЕР ЗА БАЊАЊЕ", "category": "Хигиена"},

    # --- ДОМАЌИНСТВО ---
    {"product_name": "САПУН", "category": "Домаќинство"},
    {"product_name": "ДЕТСКИ САПУН", "category": "Домаќинство"},
    {"product_name": "АНТИБАКТЕРИСКИ САПУН", "category": "Домаќинство"},
    {"product_name": "ДЕТЕРГЕНТ", "category": "Домаќинство"},
    {"product_name": "ДЕТЕРГЕНТ ЗА БОИ", "category": "Домаќинство"},
    {"product_name": "ДЕТЕРГЕНТ ЗА БЕЛО", "category": "Домаќинство"},
    {"product_name": "ТЕЧЕН ДЕТЕРГЕНТ", "category": "Домаќинство"},
    {"product_name": "ОМЕКНУВАЧ", "category": "Домаќинство"},
    {"product_name": "ОМЕКНУВАЧ СО МИРИС", "category": "Домаќинство"},
    {"product_name": "ТОАЛЕТНА ХАРТИЈА", "category": "Домаќинство"},
    {"product_name": "ТОАЛЕТНА ХАРТИЈА 3 СЛОЈА", "category": "Домаќинство"},
    {"product_name": "ХАРТИЕНИ САЛФЕТКИ", "category": "Домаќинство"},
    {"product_name": "КУЈНСКИ ПЕШКИРИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА САДОВИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА ПРОЗОРЦИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА ПОДОВИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА БАЊИ", "category": "Домаќинство"},
    {"product_name": "СРЕДСТВО ЗА ВЦ", "category": "Домаќинство"},
    {"product_name": "УНИВЕРЗАЛНО СРЕДСТВО", "category": "Домаќинство"},
    {"product_name": "СУНЃЕРИ ЗА МИЕЊЕ", "category": "Домаќинство"},
    {"product_name": "РАКАВИЦИ ЗА МИЕЊЕ", "category": "Домаќинство"},
    {"product_name": "ГУМЕНИ РАКАВИЦИ", "category": "Домаќинство"},
    {"product_name": "ЃУБРЕТАРСКИ КЕСИ ЗА ЃУБРЕ", "category": "Домаќинство"},
    {"product_name": "АЛУМИНИУМСКА ФОЛИЈА", "category": "Домаќинство"},
    {"product_name": "ПЛАСТИЧНА ФОЛИЈА", "category": "Домаќинство"},
    {"product_name": "ПЕКАРСКА ХАРТИЈА", "category": "Домаќинство"},
    {"product_name": "ХАРТИЈА ЗА ГОТВЕЊЕ", "category": "Домаќинство"},
    {"product_name": "КРПА ЗА ЧИСТЕЊЕ", "category": "Домаќинство"},
    {"product_name": "МЕТЛА", "category": "Домаќинство"},
    {"product_name": "ЧЕТКА ЗА ЧИСТЕЊЕ", "category": "Домаќинство"},
    {"product_name": "АМОНИЈАК", "category": "Домаќинство"},
    {"product_name": "СОДА БИКАРБОНА", "category": "Домаќинство"},
    {"product_name": "ОСОВЕЖУВАЧ ЗА ВОЗДУХ", "category": "Домаќинство"},
    {"product_name": "СВЕЌИ", "category": "Домаќинство"},
    {"product_name": "ТОРБА ЗА ПАЗАРЊЕ", "category": "Домаќинство"},


    # --- ЕЛЕКТРОНИКА ---
    {"product_name": "ТЕЛЕВИЗОР", "category": "Електроника"},
    {"product_name": "ЛЕД ТВ", "category": "Електроника"},
    {"product_name": "СМАРТ ТВ", "category": "Електроника"},
    {"product_name": "4К ТЕЛЕВИЗОР", "category": "Електроника"},
    {"product_name": "МОБИЛЕН ТЕЛЕФОН", "category": "Електроника"},
    {"product_name": "АНДРОИД ТЕЛЕФОН", "category": "Електроника"},
    {"product_name": "ЛАПТОП", "category": "Електроника"},
    {"product_name": "ГЕЈМИНГ ЛАПТОП", "category": "Електроника"},
    {"product_name": "ТАБЛЕТ", "category": "Електроника"},
    {"product_name": "АЈПЕД", "category": "Електроника"},
    {"product_name": "МИКРОБРАН", "category": "Електроника"},
    {"product_name": "МИКРОБРАНОВА ПЕЧКА", "category": "Електроника"},
    {"product_name": "ФРИЖИДЕР", "category": "Електроника"},
    {"product_name": "КОМБИНИРАН ФРИЖИДЕР", "category": "Електроника"},
    {"product_name": "МИНИ ФРИЖИДЕР", "category": "Електроника"},
    {"product_name": "ПЕГЛА", "category": "Електроника"},
    {"product_name": "ПАРНА ПЕГЛА", "category": "Електроника"},
    {"product_name": "ТАСТАТУРА", "category": "Електроника"},
    {"product_name": "МЕХАНИЧКА ТАСТАТУРА", "category": "Електроника"},
    {"product_name": "БЕЗЖИЧНА ТАСТАТУРА", "category": "Електроника"},
    {"product_name": "ПЕЧКА", "category": "Електроника"},
    {"product_name": "ЕЛЕКТРИЧНА ПЕЧКА", "category": "Електроника"},
    {"product_name": "РЕРНА", "category": "Електроника"},
    {"product_name": "ЕЛЕКТРИЧНА РЕРНА", "category": "Електроника"},
    {"product_name": "МАШИНА ЗА ПЕРЕЊЕ", "category": "Електроника"},
    {"product_name": "МАШИНА СО СУШЕЊЕ", "category": "Електроника"},
    {"product_name": "МАШИНА ЗА САДОВИ", "category": "Електроника"},
    {"product_name": "ЗАМРЗНУВАЧ", "category": "Електроника"},
    {"product_name": "ФРИЖИДЕР-ЗАМРЗНУВАЧ", "category": "Електроника"},
    {"product_name": "КЛИМА", "category": "Електроника"},
    {"product_name": "ИНВЕРТЕР КЛИМА", "category": "Електроника"},
    {"product_name": "МОБИЛНА КЛИМА", "category": "Електроника"},
    {"product_name": "ЗВУЧНИК", "category": "Електроника"},
    {"product_name": "БЛУТУТ ЗВУЧНИК", "category": "Електроника"},
    {"product_name": "СЛУШАЛКИ", "category": "Електроника"},
    {"product_name": "БЕЗЖИЧНИ СЛУШАЛКИ", "category": "Електроника"},
    {"product_name": "КАБЕЛ", "category": "Електроника"},
    {"product_name": "УСБ КАБЕЛ", "category": "Електроника"},
    {"product_name": "ПРОДОЛЖЕН КАБЕЛ", "category": "Електроника"},
    {"product_name": "БАТЕРИИ", "category": "Електроника"},
    {"product_name": "АА БАТЕРИИ", "category": "Електроника"},
    {"product_name": "ААА БАТЕРИИ", "category": "Електроника"},
    {"product_name": "ПОЛНАЧКИ БАТЕРИИ", "category": "Електроника"},
    {"product_name": "ПОЛНАЧ", "category": "Електроника"},
    {"product_name": "БРЗ ПОЛНАЧ", "category": "Електроника"},
    {"product_name": "БЕЗЖИЧЕН ПОЛНАЧ", "category": "Електроника"},
    {"product_name": "ФОТОАПАРАТ", "category": "Електроника"},
    {"product_name": "ДИГИТАЛЕН ФОТОАПАРАТ", "category": "Електроника"},
    {"product_name": "ВЕБКАМЕРА", "category": "Електроника"},
    {"product_name": "РОУТЕР", "category": "Електроника"},
    {"product_name": "ПРИНТЕР", "category": "Електроника"},
    {"product_name": "СКЕНЕР", "category": "Електроника"},
    {"product_name": "МОНИТОР", "category": "Електроника"},
    {"product_name": "ГЕЈМИНГ МОНИТОР", "category": "Електроника"},
    {"product_name": "4К МОНИТОР", "category": "Електроника"},
    {"product_name": "ХАРД ДИСК", "category": "Електроника"},
    {"product_name": "ССД ДИСК", "category": "Електроника"},
    {"product_name": "УСБ ФЛЕШ", "category": "Електроника"},
    {"product_name": "МЕМОРИСКА КАРТИЧКА", "category": "Електроника"},
    {"product_name": "ФИЛМ ЗА ТЕЛЕФОН", "category": "Електроника"},
    {"product_name": "МАСКА ЗА ТЕЛЕФОН", "category": "Електроника"},
    {"product_name": "ДРЖАЧ ЗА ТЕЛЕФОН", "category": "Електроника"},
]